version: "3"

services:
  server:
    build: ./server
    command: adev runserver
    environment:
      AIO_APP_PATH: ${AIO_APP_PATH}
      APP_COOKIE_SECRET: ${APP_COOKIE_SECRET}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./server:/app
    ports:
      - 8000:8000

  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
      - 35729:35729

  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    #run in bash: psql -h localhost -U postgres 
