version: "3"

services:
  web:
    build: ./polls
    # command: python aiohttp_polls/main.py
    volumes:
      - ./polls:/app
    ports:
      - "8000:8080"

  db:
    image: postgres:9.4
    # container_name: db
    restart: always
    # environment:
      # - POSTGRES_PASSWORD=postgress
      # - POSTGRES_USER=postgres
      # - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    # command: /bin/bash
    # networks:
    #   - backend

volumes:
  db-data:

# networks:
#   frontend:
#   backend:
