version: "3"

services:
  web:
    build: ./polls
    # command: python aiohttp_polls/main.py
    volumes:
      - ./polls:/app
    ports:
      - "8000:8080"

  db:
    image: postgres:9.4
    # container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    # networks:
    #   - backend
    ports:
      - "5432:5432"

volumes:
  db-data:

# networks:
#   frontend:
#   backend:
