version: "3"

services:
  web:
    build: ./polls
    # command: python aiohttp_polls/main.py
    volumes:
      - ./polls:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    #run in bash: psql -h localhost -U postgres 
