version: "3"

services:
  server:
    build: ./server
    # command: python aiohttp_polls/main.py
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    #run in bash: psql -h localhost -U postgres 
