version: "3"

services:
  web:
    build: ./polls
    volumes:
      - ./polls:/app
    ports:
      - "5000:5000"

  db:
    image: postgres:9.4
    # container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
