version: "3"

services:
  server:
    build: ./server
    command: adev runserver
    environment:
      AIO_APP_PATH: ${APP_PATH}
      APP_DB_NAME: ${POSTGRES_DB}
      APP_DB_USER: ${POSTGRES_USER}
      APP_DB_PASSWORD: ${POSTGRES_PASSWORD}
      APP_COOKIE_SECRET: ${COOKIE_SECRET}
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    depends_on: 
      - db
      - redis

  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
      - 35729:35729

  redis:
    image: redis:alpine
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379

  db:
    image: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    #run in bash: psql -h localhost -U postgres 
