version: "3"

services:
  web:
    build: ./polls
    restart: always
    volumes:
      - ./polls:/app
    ports:
      - 8000:8080

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgress
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    #run in bash: psql -h localhost -U postgres 