version: "3"

services:
  web:
    build: ./polls
    # command: bash
    command: adev serve aiohttp_polls/
    volumes:
      - ./polls:/app
    ports:
      - 8000:8000

  db:
    image: postgres:9.4
    # container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    # networks:
    #   - backend
    ports:
      - 5433:5432

volumes:
  db-data:

# networks:
#   frontend:
#   backend:
